IMAGE_NAME=cloud-init-base-alpine
IMAGE_VERSION=0.4.3
IMAGE_PACKER_MODULE=images-from-snapshot
IMAGE_SOURCE=vultr.cloud-init-alpine-image
IMAGE_TEST_TYPE=cloud-init-image

export

%:
	$(MAKE) -f Makefile.common "$@"

