IMAGE_NAME=vaulted-base-alpine
IMAGE_VERSION=0.1.6
IMAGE_PACKER_MODULE=images-from-snapshot
IMAGE_SOURCE=vultr.cloud-init-alpine-image
IMAGE_TEST_TYPE=cloud-init-image
IMAGE_PACKAGES=["curl", "jq"]

export

%:
	$(MAKE) -f Makefile.common "$@"
